### ISSUE TITLE
Error with alltabs:true and unsaved tab

### ISSUE THREAD

**Issue by tuzemec** [jugyo/SublimeSuperNavigator#2]
Pretty nice plugin! :-)
But I've just discovered a little glitch.
When you have a tab that have never been saved and try to call `super_navigate {"allTabs": true}` it throws the following error:

```
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 356, in run_
    return self.run(edit, **args)
  File ".\SuperNavigator.py", line 7, in run
  File ".\SuperNavigator.py", line 25, in navigate
  File ".\ntpath.py", line 198, in basename
  File ".\ntpath.py", line 170, in split
  File ".\ntpath.py", line 125, in splitdrive
TypeError: 'NoneType' object is unsubscriptable
```

It's the same both with ST2 and ST3

**Comment by jugyo** [comment]
Oh, I see. My bad. It doesn't work for 'untitled' tabs now. I'll fix it.

**Comment by jugyo** [comment]
I've fixed it so please retry.

**Comment by tuzemec** [comment]
Perfect! 
Thank you!
